#include "bsw_adc.h"
#include "adc.h"

static volatile uint16_t   s_latest_ad = 0U;
static BSW_ADC_Callback_t  s_callback  = 0;

void BSW_ADC_Start(void)
{
    HAL_ADCEx_Calibration_Start(&hadc1);

    /* NVIC for ADC1_2 (not generated by CubeMX; enabled here in BSW) */
    HAL_NVIC_SetPriority(ADC1_2_IRQn, 1U, 0U);
    HAL_NVIC_EnableIRQ(ADC1_2_IRQn);

    /* Start ADC in interrupt mode; TIM1_CC3 external trigger fires conversions */
    HAL_ADC_Start_IT(&hadc1);
}

void BSW_ADC_RegisterCallback(BSW_ADC_Callback_t cb)
{
    s_callback = cb;
}

uint16_t BSW_ADC_GetLatestAD(void)
{
    return s_latest_ad;
}

/* ------------------------------------------------------------------ */
/*  IRQ handler  (ADC1 and ADC2 share one vector on STM32F1)          */
/* ------------------------------------------------------------------ */
void ADC1_2_IRQHandler(void)
{
    HAL_ADC_IRQHandler(&hadc1);
}

/* ------------------------------------------------------------------ */
/*  HAL callback : called after each TIM1_CC3-triggered conversion     */
/*  Re-arms ADC so the next TIM1_CC3 event triggers another sample.   */
/* ------------------------------------------------------------------ */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1) {
        s_latest_ad = (uint16_t)HAL_ADC_GetValue(hadc);
        HAL_ADC_Start_IT(hadc);     /* re-arm for next external trigger */

        if (s_callback != 0) {
            s_callback();           /* notify upper layer every PWM cycle */
        }
    }
}
